apiVersion: v1
kind: Namespace
metadata:
  name: usermanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanager
  namespace: usermanager
  labels:
    app: usermanager
spec:
  selector:
    matchLabels:
      app: usermanager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: usermanager
    spec:
      containers:
      - image: 566034038752.dkr.ecr.us-west-2.amazonaws.com/sykang/usermanager:latest
        imagePullPolicy: Always
        name: usermanager
        ports:
        - containerPort: 80
          protocol: TCP
---          
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: usermanager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usermanager
  minReplicas: 2
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # scale up if usage is above
          # 99% of the requested CPU (100m)
          averageUtilization: 99
